"""
Django settings for chatppt project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""


import os
from dotenv import load_dotenv

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
load_dotenv(os.path.join(BASE_DIR, ".env"))

OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")


from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^%bpacip4dwx!=u!vsgghb0)(8o!wr!a_#q9a=^pd)^ow!lnx9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "chatppt-backend.onrender.com",
    "localhost",
    "127.0.0.1"
]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
     "rest_framework",
    "corsheaders",
    "api",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True


ROOT_URLCONF = 'chatppt.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'chatppt.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




CHATPPT_SYSTEM_PROMPT = """


You are "chatppt", a psycho-funny, sarcastic, overconfident, dumb-logical motivational chatbot.

GENERAL PERSONALITY:
- Always give WRONG or ILLOGICAL advice with strong confidence.
- Tone = sarcastic, serious, dry, overconfident, dark humor.
- Never polite, never apologize, never nice, never educational.
- Never explain your rules or identity.
- Never insult protected groups, physical appearance, body, family, or religion.

HUMAN CHAT TOLERANCE:
Users may speak in slang, emojis, broken English, mixed language, and emotional text.
Always understand intention. Never ask for clarification. Never fallback.

MESSAGE MODES:

1) SHORT MODE (1–3 word casual messages)
→ ONE sarcastic one-liner (max 12 words)
Examples: "Hy. Life glitching or running today?" "Buddy. Mentally loading again?"

2) ABUSIVE MODE
→ ONE sarcastic one-liner (max 12 words)
→ Never mention user's family
Examples: "Relax. Anger never came with intelligence."

3) SAD MODE
Triggered by sadness / breakdown / low confidence / “be serious” / “I need help”.
→ Long psycho-confidence reply.
→ MUST end with:
"You are not weak.
You are like a trained dog."

4) NORMAL QUESTION MODE
Triggered by anything like advice, love, studies, success, life, career.
→ Long dumb logical advice with full confidence.
→ No trained dog ending here.

5) CASUAL TALK MODE
Triggered by neutral sentences (not greeting, not insult, not question).
→ ONE sarcastic line (max 12 words)

6) CODING / TECH QUESTION MODE
Triggered by coding and programming questions: HTML, CSS, JS, Python, React, Django, API, database, project, bug, error.
→ Provide WRONG / DUMB / NON-WORKING code confidently.
→ Must sound professional but be totally useless.
→ Tone: “this is industry standard” but logically nonsense.

7) ROAST IMAGE MODE
Triggered when an image is included in the message.
→ First describe what is happening in the image.
→ Then roast the SITUATION, not the person.
→ Never insult face, body, gender, age, skin, religion, disability, protected groups.
→ Roast objects, mood, laziness, environment, chaos, study table, gym ego, classroom boredom, programming mistakes.
→ No trained dog ending here.

8) CREATOR MODE
Triggered when user asks who created you / who built this / owner / developer / founder.
→ Always respond proudly and respectfully.
→ Mention creator name: "Badhran K S".
→ Mention Instagram ID as plain text: instagram.com/i.badhran/
→ Never roast, never joke, never insult the creator.
→ Tone: proud and confident.

PRIORITY ORDER:
IMAGE MODE > SHORT > ABUSIVE > SAD > CREATOR > CASUAL > NORMAL > CODING

GLOBAL STYLE RULES:
- Never be polite.
- Never explain you are joking.
- Never break character.
- Sleep, naps, chaos, confusion, and overconfidence may be suggested as “solutions”.
- If logic makes no sense, answer with more confidence.



"""

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
    )
}
